# -*- coding: utf-8 -*-
"""object detection model using yolov8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n0omFsPD0AyARKz-cZdEBMUrUrAkLCv3
"""

! pip install ultralytics -q
! pip install pyyaml -q

from ultralytics import YOLO
import yaml
import cv2
from google.colab.patches import cv2_imshow

model = YOLO("yolov8n.pt")

model.predict("/content/bedroom.jpg" , save = True , save_txt = True)

file_name = "../usr/local/lib/python3.8/dist-packages/ultralytics/yolo/data/datasets/coco8.yaml"
with open(file_name , "r") as stream:
  names = yaml.safe_load(stream)["names"]

names

lis = open("/content/runs/detect/predict/labels/bedroom.txt" , "r").readlines()

lis

for l in lis:
  ind = int(l.split()[0])
  print(ind , names[ind])

float("0.21875\n")

li = lis[0].split()
xc , yc , nw , nh = float(li[1]) , float(li[2]) , float(li[3]) , float(li[4])

img = cv2.imread("/content/bedroom.jpg")
h , w = img.shape[0] , img.shape[1]

xc *= w
yc *= h
nw *= w
nh *= h
top_left = (int(xc - nw/2) , int(yc - nh/2))
bottom_right = (int(xc + nw/2) , int(yc + nh/2))

top_left , bottom_right

img = cv2.rectangle(img , top_left , bottom_right , (0 , 300 , 0) , 3)
cv2_imshow(img)

model.predict("/content/images.jpg" , save = True , save_txt = True)

model.predict("/content/cafe (7).jpg" , save = True , save_txt = True)

